/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from '../common';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';

export interface CloneFactoryMockInterface extends utils.Interface {
  functions: {
    '__calculateCloneDeploymentAddress(bytes32)': FunctionFragment;
    '__deployClone()': FunctionFragment;
    '__deployClone(bytes32)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | '__calculateCloneDeploymentAddress'
      | '__calculateCloneDeploymentAddress(bytes32)'
      | '__deployClone()'
      | '__deployClone(bytes32)',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: '__calculateCloneDeploymentAddress',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: '__calculateCloneDeploymentAddress(bytes32)',
    values: [BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: '__deployClone()',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: '__deployClone(bytes32)',
    values: [BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: '__calculateCloneDeploymentAddress',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__calculateCloneDeploymentAddress(bytes32)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__deployClone()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__deployClone(bytes32)',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface CloneFactoryMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CloneFactoryMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __calculateCloneDeploymentAddress(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    '__calculateCloneDeploymentAddress(bytes32)'(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    '__deployClone()'(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    '__deployClone(bytes32)'(
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  __calculateCloneDeploymentAddress(
    salt: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  '__calculateCloneDeploymentAddress(bytes32)'(
    salt: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  '__deployClone()'(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  '__deployClone(bytes32)'(
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    __calculateCloneDeploymentAddress(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;

    '__calculateCloneDeploymentAddress(bytes32)'(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;

    '__deployClone()'(overrides?: CallOverrides): Promise<string>;

    '__deployClone(bytes32)'(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    __calculateCloneDeploymentAddress(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    '__calculateCloneDeploymentAddress(bytes32)'(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    '__deployClone()'(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    '__deployClone(bytes32)'(
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __calculateCloneDeploymentAddress(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    '__calculateCloneDeploymentAddress(bytes32)'(
      salt: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    '__deployClone()'(
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    '__deployClone(bytes32)'(
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
