/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from '../../common';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';

export interface ERC1271OwnableMockInterface extends utils.Interface {
  functions: {
    '__isValidSignature(bytes32,bytes)': FunctionFragment;
    'isValidSignature(bytes32,bytes)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | '__isValidSignature'
      | '__isValidSignature(bytes32,bytes)'
      | 'isValidSignature'
      | 'isValidSignature(bytes32,bytes)',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: '__isValidSignature',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: '__isValidSignature(bytes32,bytes)',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isValidSignature',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isValidSignature(bytes32,bytes)',
    values: [BytesLike, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: '__isValidSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__isValidSignature(bytes32,bytes)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isValidSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isValidSignature(bytes32,bytes)',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface ERC1271OwnableMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC1271OwnableMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string] & { magicValue: string }>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string] & { magicValue: string }>;
  };

  __isValidSignature(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  '__isValidSignature(bytes32,bytes)'(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  isValidSignature(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  'isValidSignature(bytes32,bytes)'(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  callStatic: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
