/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from '../../common';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';

export interface ERC1271StoredMockInterface extends utils.Interface {
  functions: {
    '__isValidSignature(bytes32,bytes)': FunctionFragment;
    '__setValidSignature(bytes32,bool)': FunctionFragment;
    'isValidSignature(bytes32,bytes)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | '__isValidSignature'
      | '__isValidSignature(bytes32,bytes)'
      | '__setValidSignature'
      | '__setValidSignature(bytes32,bool)'
      | 'isValidSignature'
      | 'isValidSignature(bytes32,bytes)',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: '__isValidSignature',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: '__isValidSignature(bytes32,bytes)',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: '__setValidSignature',
    values: [BytesLike, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: '__setValidSignature(bytes32,bool)',
    values: [BytesLike, boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'isValidSignature',
    values: [BytesLike, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'isValidSignature(bytes32,bytes)',
    values: [BytesLike, BytesLike],
  ): string;

  decodeFunctionResult(
    functionFragment: '__isValidSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__isValidSignature(bytes32,bytes)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__setValidSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__setValidSignature(bytes32,bool)',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isValidSignature',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isValidSignature(bytes32,bytes)',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface ERC1271StoredMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ERC1271StoredMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>;

    __setValidSignature(
      hash: BytesLike,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    '__setValidSignature(bytes32,bool)'(
      hash: BytesLike,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string] & { magicValue: string }>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string] & { magicValue: string }>;
  };

  __isValidSignature(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  '__isValidSignature(bytes32,bytes)'(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  __setValidSignature(
    hash: BytesLike,
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  '__setValidSignature(bytes32,bool)'(
    hash: BytesLike,
    status: boolean,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  isValidSignature(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  'isValidSignature(bytes32,bytes)'(
    hash: BytesLike,
    signature: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>;

  callStatic: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    __setValidSignature(
      hash: BytesLike,
      status: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;

    '__setValidSignature(bytes32,bool)'(
      hash: BytesLike,
      status: boolean,
      overrides?: CallOverrides,
    ): Promise<void>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    __setValidSignature(
      hash: BytesLike,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    '__setValidSignature(bytes32,bool)'(
      hash: BytesLike,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    '__isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    __setValidSignature(
      hash: BytesLike,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    '__setValidSignature(bytes32,bool)'(
      hash: BytesLike,
      status: boolean,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'isValidSignature(bytes32,bytes)'(
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;
  };
}
