import taskBuild from './tasks/build.ts';
import taskGenerateBytes32Builder from './tasks/generate_bytes32_builder.ts';
import taskGenerateEip712 from './tasks/generate_eip_712.ts';
import taskOrganizeTestFiles from './tasks/organize_test_files.ts';
import taskRenameEntity from './tasks/rename_entity.ts';
import taskScaffoldContract from './tasks/scaffold_contract.ts';
import HardhatExposed from './vendor/hardhat-exposed/plugin.ts';
import HardhatEthers from '@nomicfoundation/hardhat-ethers';
import HardhatEthersChaiMatchers from '@nomicfoundation/hardhat-ethers-chai-matchers';
import HardhatMocha from '@nomicfoundation/hardhat-mocha';
import HardhatNetworkHelpers from '@nomicfoundation/hardhat-network-helpers';
import HardhatTypechain from '@nomicfoundation/hardhat-typechain';
import HardhatAbiExporter from '@solidstate/hardhat-abi-exporter';
import HardhatContractSizer from '@solidstate/hardhat-contract-sizer';
import HardhatLicenseIdentifier from '@solidstate/hardhat-license-identifier';
import HardhatLinearization from '@solidstate/hardhat-linearization';
import HardhatSelectorUploader from '@solidstate/hardhat-selector-uploader';
import { type HardhatUserConfig } from 'hardhat/config';
import path from 'node:path';

const config: HardhatUserConfig = {
  plugins: [
    HardhatEthers,
    HardhatEthersChaiMatchers,
    HardhatMocha,
    HardhatNetworkHelpers,
    HardhatTypechain,
    HardhatAbiExporter,
    HardhatContractSizer,
    HardhatLicenseIdentifier,
    HardhatLinearization,
    HardhatSelectorUploader,
    HardhatExposed,
  ],

  tasks: [
    taskBuild,
    taskGenerateBytes32Builder,
    taskGenerateEip712,
    taskOrganizeTestFiles,
    taskRenameEntity,
    taskScaffoldContract,
  ],

  networks: {
    default: {
      type: 'edr-simulated',
      allowUnlimitedContractSize: true,
    },
  },

  solidity: {
    version: '0.8.35',
    settings: {
      evmVersion: 'cancun',
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },

  typechain: {
    outDir: path.resolve(import.meta.dirname, 'typechain-types'),
  },

  abiExporter: {
    runOnCompile: true,
    clear: true,
    flat: true,
    // do not export internal or test ABIs, including those generated by hardhat-exposed
    except: [/_.*/, /.*Test$/, /[$].*/],
  },

  licenseIdentifier: {
    overwrite: false,
    runOnCompile: true,
  },
};

export default config;
