import './tasks/compile';
import './tasks/generate_bytes32_builder';
import './tasks/generate_eip_712';
import './tasks/organize_test_files';
import './tasks/rename_entity';
import './tasks/scaffold_contract';
import HardhatEthers from '@nomicfoundation/hardhat-ethers';
import HardhatEthersChaiMatchers from '@nomicfoundation/hardhat-ethers-chai-matchers';
import HardhatTypechain from '@nomicfoundation/hardhat-typechain';
import HardhatAbiExporter from '@solidstate/hardhat-abi-exporter';
import HardhatContractSizer from '@solidstate/hardhat-contract-sizer';
import HardhatLicenseIdentifier from '@solidstate/hardhat-license-identifier';
import HardhatSelectorUploader from '@solidstate/hardhat-selector-uploader';
import 'hardhat-exposed';
import 'hardhat-gas-reporter';
import 'hardhat-linearization';
import { type HardhatUserConfig } from 'hardhat/config';
import 'solidity-coverage';

const config: HardhatUserConfig = {
  plugins: [
    HardhatEthers,
    HardhatEthersChaiMatchers,
    HardhatTypechain,
    HardhatAbiExporter,
    HardhatContractSizer,
    HardhatLicenseIdentifier,
    HardhatSelectorUploader,
  ],

  networks: {
    hardhat: {
      type: 'edr',
      allowUnlimitedContractSize: true,
    },
  },

  solidity: {
    version: '0.8.29',
    settings: {
      evmVersion: 'cancun',
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },

  abiExporter: {
    runOnCompile: true,
    clear: true,
    flat: true,
    // do not export internal or test ABIs, including those generated by hardhat-exposed
    except: [/_.*/, /.*Test$/, /[$].*/],
  },

  gasReporter: {
    enabled: true,
    reportPureAndViewMethods: true,
    outputFile: './gasreport.txt',
  },

  licenseIdentifier: {
    overwrite: false,
    runOnCompile: true,
  },
};

export default config;
