export default {
  rules: {
    curly: 'off',
    'explicit-types': 'error',
    'id-denylist': 'error',
    'imports-on-top': 'error',
    'max-state-vars': 'error',
    'named-return-params': 'error',
    'naming-convention': 'off',
    'no-console': 'error',
    'no-default-visibility': 'error',
    'no-duplicate-imports': 'error',
    'no-empty-blocks': 'error',
    'no-global-imports': 'error',
    'no-restricted-syntax': 'error',
    'no-send': 'error',
    'no-tx-origin': 'error',
    'no-uninitialized-immutable-references': 'error',
    'no-unused-vars': 'error',
    'private-vars': 'off',
    'require-revert-reason': 'error',
    'sort-imports': 'error',
    'sort-modifiers': 'error',
  },
};
