/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ECDSAMultisigWallet__factory } from './ECDSAMultisigWallet__factory';
export { ECDSAMultisigWalletMock__factory } from './ECDSAMultisigWalletMock__factory';
