/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MinimalProxyFactoryMockInterface extends ethers.utils.Interface {
  functions: {
    "calculateMinimalProxyDeploymentAddress(address,bytes32)": FunctionFragment;
    "deployMinimalProxy(address,bytes32)": FunctionFragment;
    "generateMinimalProxyInitCode(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateMinimalProxyDeploymentAddress",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMinimalProxy",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateMinimalProxyInitCode",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateMinimalProxyDeploymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMinimalProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateMinimalProxyInitCode",
    data: BytesLike
  ): Result;

  events: {};
}

export class MinimalProxyFactoryMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MinimalProxyFactoryMockInterface;

  functions: {
    calculateMinimalProxyDeploymentAddress(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "calculateMinimalProxyDeploymentAddress(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "deployMinimalProxy(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deployMinimalProxy(address)"(
      target: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    generateMinimalProxyInitCode(
      target: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "generateMinimalProxyInitCode(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  calculateMinimalProxyDeploymentAddress(
    target: string,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "calculateMinimalProxyDeploymentAddress(address,bytes32)"(
    target: string,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "deployMinimalProxy(address,bytes32)"(
    target: string,
    salt: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deployMinimalProxy(address)"(
    target: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  generateMinimalProxyInitCode(
    target: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "generateMinimalProxyInitCode(address)"(
    target: string,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    calculateMinimalProxyDeploymentAddress(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "calculateMinimalProxyDeploymentAddress(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployMinimalProxy(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "deployMinimalProxy(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<string>;

    generateMinimalProxyInitCode(
      target: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "generateMinimalProxyInitCode(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    calculateMinimalProxyDeploymentAddress(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calculateMinimalProxyDeploymentAddress(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "deployMinimalProxy(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deployMinimalProxy(address)"(
      target: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    generateMinimalProxyInitCode(
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "generateMinimalProxyInitCode(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateMinimalProxyDeploymentAddress(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calculateMinimalProxyDeploymentAddress(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "deployMinimalProxy(address,bytes32)"(
      target: string,
      salt: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deployMinimalProxy(address)"(
      target: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    generateMinimalProxyInitCode(
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "generateMinimalProxyInitCode(address)"(
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
