/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  MetamorphicFactory,
  MetamorphicFactoryInterface,
} from "../MetamorphicFactory";

const _abi = [
  {
    inputs: [],
    name: "getMetamorphicImplementation",
    outputs: [
      {
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class MetamorphicFactory__factory {
  static readonly abi = _abi;
  static createInterface(): MetamorphicFactoryInterface {
    return new utils.Interface(_abi) as MetamorphicFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MetamorphicFactory {
    return new Contract(address, _abi, signerOrProvider) as MetamorphicFactory;
  }
}
