/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { SafeOwnable, SafeOwnableInterface } from "../SafeOwnable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nomineeOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610314806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806379ba5097146100515780638ab5150a1461005b5780638da5cb5b1461007f578063f2fde38b14610087575b600080fd5b61005961009a565b005b6100636101b6565b6040516001600160a01b03909116815260200160405180910390f35b6100636101d7565b610059610095366004610290565b6101ff565b6000805160206102bf833981519152546001600160a01b031633146101185760405162461bcd60e51b815260206004820152602960248201527f536166654f776e61626c653a2073656e646572206d757374206265206e6f6d696044820152683732b29037bbb732b960b91b60648201526084015b60405180910390fd5b7f8a22373512790c48b83a1fe2efdd2888d4a917bcdc24d0adf63e60f671680460805460405133916001600160a01b0316907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e090600090a380546001600160a01b031916331781556101b360006000805160206102bf8339815191525b9081546001600160a01b0319166001600160a01b0391909116179055565b50565b60006000805160206102bf8339815191525b546001600160a01b0316919050565b60007f8a22373512790c48b83a1fe2efdd2888d4a917bcdc24d0adf63e60f6716804606101c8565b7f8a22373512790c48b83a1fe2efdd2888d4a917bcdc24d0adf63e60f671680460546001600160a01b031633146102785760405162461bcd60e51b815260206004820152601d60248201527f4f776e61626c653a2073656e646572206d757374206265206f776e6572000000604482015260640161010f565b6101b3816000805160206102bf833981519152610195565b6000602082840312156102a1578081fd5b81356001600160a01b03811681146102b7578182fd5b939250505056fe24aa1f7b31fd188a8d3ecfb06bc55c806040e59b03bd4396283442fce6617890a2646970667358221220549d54ce941e48e51fb0fb45cd47ee4f2943239913ad535c7417890d0048645664736f6c63430008040033";

export class SafeOwnable__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SafeOwnable> {
    return super.deploy(overrides || {}) as Promise<SafeOwnable>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SafeOwnable {
    return super.attach(address) as SafeOwnable;
  }
  connect(signer: Signer): SafeOwnable__factory {
    return super.connect(signer) as SafeOwnable__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SafeOwnableInterface {
    return new utils.Interface(_abi) as SafeOwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SafeOwnable {
    return new Contract(address, _abi, signerOrProvider) as SafeOwnable;
  }
}
