/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Diamond } from './Diamond';
export type { DiamondBase } from './DiamondBase';
export type { DiamondBaseMock } from './DiamondBaseMock';
export type { DiamondBaseStorage } from './DiamondBaseStorage';
export type { DiamondCuttable } from './DiamondCuttable';
export type { DiamondCuttableMock } from './DiamondCuttableMock';
export type { DiamondLoupe } from './DiamondLoupe';
export type { DiamondLoupeMock } from './DiamondLoupeMock';
export type { DiamondMock } from './DiamondMock';
export type { IDiamondCuttable } from './IDiamondCuttable';
export type { IDiamondLoupe } from './IDiamondLoupe';
