/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Extended } from './ERC20Extended';
export type { ERC20ExtendedMock } from './ERC20ExtendedMock';
