/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UpgradeableProxy } from './UpgradeableProxy';
export type { UpgradeableProxyMock } from './UpgradeableProxyMock';
export type { UpgradeableProxyOwnable } from './UpgradeableProxyOwnable';
export type { UpgradeableProxyOwnableMock } from './UpgradeableProxyOwnableMock';
