/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from './base';
export * as ownable from './ownable';
export * as stored from './stored';
export { IERC1271__factory } from './IERC1271__factory';
