/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  ManagedProxyOwnable,
  ManagedProxyOwnableInterface,
} from '../../../proxy/managed/ManagedProxyOwnable';
import type { Provider } from '@ethersproject/providers';
import { Contract, Signer, utils } from 'ethers';

const _abi = [
  {
    stateMutability: 'payable',
    type: 'fallback',
  },
];

export class ManagedProxyOwnable__factory {
  static readonly abi = _abi;
  static createInterface(): ManagedProxyOwnableInterface {
    return new utils.Interface(_abi) as ManagedProxyOwnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): ManagedProxyOwnable {
    return new Contract(address, _abi, signerOrProvider) as ManagedProxyOwnable;
  }
}
