/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as base from './base';

export type { base };
export type { ERC4626 } from './ERC4626';
export type { ERC4626Mock } from './ERC4626Mock';
export type { IERC4626 } from './IERC4626';
export type { IERC4626Internal } from './IERC4626Internal';
