/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc20 from './ERC20';
import type * as erc721 from './ERC721';
import type * as erc1155 from './ERC1155';
import type * as erc1404 from './ERC1404';
import type * as erc4626 from './ERC4626';

export type { erc1155 };

export type { erc1404 };

export type { erc20 };

export type { erc4626 };

export type { erc721 };
