/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ReentrancyGuardMock,
  ReentrancyGuardMockInterface,
} from "../ReentrancyGuardMock";

const _abi = [
  {
    inputs: [],
    name: "crossFunctionReentrancyTest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nonReentrancyTest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "reentrancyTest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101da806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806322a1e4e11461004657806345a2556914610050578063dd09946114610050575b600080fd5b61004e610058565b005b61004e6100d6565b7f09acf4e54214992e70883cf7dcd6957ff2c71cd9e14df4bec4383bc0d11607dc8054600214156100d05760405162461bcd60e51b815260206004820152601f60248201527f5265656e7472616e637947756172643a207265656e7472616e742063616c6c0060448201526064015b60405180910390fd5b60019055565b7f09acf4e54214992e70883cf7dcd6957ff2c71cd9e14df4bec4383bc0d11607dc8054600214156101495760405162461bcd60e51b815260206004820152601f60248201527f5265656e7472616e637947756172643a207265656e7472616e742063616c6c0060448201526064016100c7565b600281556040805163dd09946160e01b81529051309163dd09946191600480830192600092919082900301818387803b15801561018557600080fd5b505af1158015610199573d6000803e3d6000fd5b50506001909255505056fea2646970667358221220a632285f9747321edfea7826666656bb552f3ee3ffd3c7f15c3ca48b6351a49e64736f6c63430008040033";

export class ReentrancyGuardMock__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ReentrancyGuardMock> {
    return super.deploy(overrides || {}) as Promise<ReentrancyGuardMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ReentrancyGuardMock {
    return super.attach(address) as ReentrancyGuardMock;
  }
  connect(signer: Signer): ReentrancyGuardMock__factory {
    return super.connect(signer) as ReentrancyGuardMock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReentrancyGuardMockInterface {
    return new utils.Interface(_abi) as ReentrancyGuardMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ReentrancyGuardMock {
    return new Contract(address, _abi, signerOrProvider) as ReentrancyGuardMock;
  }
}
