/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Metadata } from './ERC1155Metadata';
export type { ERC1155MetadataInternal } from './ERC1155MetadataInternal';
export type { ERC1155MetadataMock } from './ERC1155MetadataMock';
export type { IERC1155Metadata } from './IERC1155Metadata';
export type { IERC1155MetadataInternal } from './IERC1155MetadataInternal';
