/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1271Stored__factory } from './ERC1271Stored__factory';
export { ERC1271StoredMock__factory } from './ERC1271StoredMock__factory';
