/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from '../../common';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';

export interface ManagedProxyOwnableMockInterface extends utils.Interface {
  functions: {
    '__getImplementation()': FunctionFragment;
    '__getManager()': FunctionFragment;
    'getOwner()': FunctionFragment;
    'setOwner(address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | '__getImplementation'
      | '__getImplementation()'
      | '__getManager'
      | '__getManager()'
      | 'getOwner'
      | 'getOwner()'
      | 'setOwner'
      | 'setOwner(address)',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: '__getImplementation',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: '__getImplementation()',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: '__getManager',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: '__getManager()',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'getOwner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'getOwner()',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'setOwner', values: [string]): string;
  encodeFunctionData(
    functionFragment: 'setOwner(address)',
    values: [string],
  ): string;

  decodeFunctionResult(
    functionFragment: '__getImplementation',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__getImplementation()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__getManager',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: '__getManager()',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getOwner()', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'setOwner(address)',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface ManagedProxyOwnableMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ManagedProxyOwnableMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __getImplementation(overrides?: CallOverrides): Promise<[string]>;

    '__getImplementation()'(overrides?: CallOverrides): Promise<[string]>;

    __getManager(overrides?: CallOverrides): Promise<[string]>;

    '__getManager()'(overrides?: CallOverrides): Promise<[string]>;

    getOwner(overrides?: CallOverrides): Promise<[string]>;

    'getOwner()'(overrides?: CallOverrides): Promise<[string]>;

    setOwner(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    'setOwner(address)'(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  __getImplementation(overrides?: CallOverrides): Promise<string>;

  '__getImplementation()'(overrides?: CallOverrides): Promise<string>;

  __getManager(overrides?: CallOverrides): Promise<string>;

  '__getManager()'(overrides?: CallOverrides): Promise<string>;

  getOwner(overrides?: CallOverrides): Promise<string>;

  'getOwner()'(overrides?: CallOverrides): Promise<string>;

  setOwner(
    owner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  'setOwner(address)'(
    owner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    __getImplementation(overrides?: CallOverrides): Promise<string>;

    '__getImplementation()'(overrides?: CallOverrides): Promise<string>;

    __getManager(overrides?: CallOverrides): Promise<string>;

    '__getManager()'(overrides?: CallOverrides): Promise<string>;

    getOwner(overrides?: CallOverrides): Promise<string>;

    'getOwner()'(overrides?: CallOverrides): Promise<string>;

    setOwner(owner: string, overrides?: CallOverrides): Promise<void>;

    'setOwner(address)'(
      owner: string,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    __getImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    '__getImplementation()'(overrides?: CallOverrides): Promise<BigNumber>;

    __getManager(overrides?: CallOverrides): Promise<BigNumber>;

    '__getManager()'(overrides?: CallOverrides): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    'getOwner()'(overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    'setOwner(address)'(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __getImplementation(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    '__getImplementation()'(
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    __getManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    '__getManager()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'getOwner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setOwner(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    'setOwner(address)'(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
