/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as diamond from './diamond';
export * as managed from './managed';
export * as upgradeable from './upgradeable';
export { Proxy__factory } from './Proxy__factory';
export { ProxyMock__factory } from './ProxyMock__factory';
