/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Base__factory } from './ERC20Base__factory';
export { ERC20BaseInternal__factory } from './ERC20BaseInternal__factory';
export { ERC20BaseMock__factory } from './ERC20BaseMock__factory';
